upstreamProjects:
  Mule-runtime/metadata-model-api/1.4.0-NOVEMBER-2023,
  Mule-runtime/mule-profiling-api/master,
  Mule-runtime/mule-api/1.4.0-NOVEMBER-2023,
  Mule-runtime/mule-extensions-api/1.4.0-NOVEMBER-2023,
  Mule-runtime/mule-artifact-ast/1.0.0-NOVEMBER-2023,
  Mule-runtime/mule-properties-api/master,
  DataWeave/data-weave/master,
  Mule-runtime/mule-maven-client/1.6.0-NOVEMBER-2023
# Comment public setting to get oldMuleArtifact 4.2.1 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true
mavenCompileGoal: clean install -U -DskipTests -DskipITs -Dinvoker.skip=true -Darchetype.test.skip -Dmaven.javadoc.skip
projectType: runtime
