upstreamProjects:
  Mule-runtime/metadata-model-api/master-MAY-2022,
  Mule-runtime/mule-profiling-api/master,
  Mule-runtime/mule-api/master-MAY-2022,
  Mule-runtime/mule-extensions-api/master-MAY-2022,
  Mule-runtime/mule-artifact-ast/master-MAY-2022,
  Mule-runtime/mule-properties-api/master,
  DataWeave/data-weave/master,
  Mule-runtime/mule-maven-client/master-MAY-2022
# Comment public setting to get oldMuleArtifact 4.2.1 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true
mavenCompileGoal: clean install -U -DskipTests -DskipITs -Dinvoker.skip=true -Darchetype.test.skip -Dmaven.javadoc.skip
projectType: runtime
