upstreamProjects:
  Mule-runtime/metadata-model-api/1.4.0-20240122-WITH-W-15141905-W-15782010,
  Mule-runtime/mule-profiling-api/1.0.0-FEBRUARY-2024,
  Mule-runtime/mule-api/1.4.0-20240122-WITH-W-15141905-W-15782010,
  Mule-runtime/mule-extensions-api/1.4.0-20240122-WITH-W-15141905-W-15782010,
  Mule-runtime/mule-artifact-ast/1.0.0-20240122-WITH-W-15141905-W-15782010,
  Mule-runtime/mule-properties-api/1.0.0-20240122-WITH-W-15141905-W-15782010,
  DataWeave/data-weave/support/2.4.0,
  Mule-runtime/mule-maven-client/1.6.0-FEBRUARY-2024
# Comment public setting to get oldMuleArtifact 4.2.1 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true
mavenCompileGoal: clean install -U -DskipTests -DskipITs -Dinvoker.skip=true -Darchetype.test.skip -Dmaven.javadoc.skip
projectType: runtime
