upstreamProjects:
  Mule-runtime/metadata-model-api/support/1.6.x,
  Mule-runtime/mule-profiling-api/support/1.2.x,
  Mule-runtime/mule-api/1.6.4-DRY-RUN,
  Mule-runtime/mule-extensions-api/support/1.6.x,
  Mule-runtime/mule-artifact-ast/support/1.2.x,
  Mule-runtime/mule-properties-api/1.2.4-DRY-RUN,
  DataWeave/data-weave/support/2.6.x,
  Mule-runtime/mule-maven-client/support/2.1.x
# Comment public setting to get oldMuleArtifact 4.2.1 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true -T1C
mavenCompileGoal: clean install -U -DskipTests -DskipITs -Dinvoker.skip=true -Darchetype.test.skip -Dmaven.javadoc.skip -P!testJdkWithoutXmlModule
projectType: runtime
jdkTool: OPEN-JDK11
testJdkTool: OPEN-JDK8
additionalTestConfigs:
  jdk11:
    testJdkTool: OPEN-JDK11
    mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true -T1C -P!testJdkWithoutXmlModule -Pjava11tests
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true -T1C -P!testJdkWithoutXmlModule
    