upstreamProjects:
  Mule-runtime/metadata-model-api/1.9.6,
  Mule-runtime/mule-profiling-api/1.5.6,
  Mule-runtime/mule-api/1.9.6,
  Mule-runtime/mule-extensions-api/1.9.6,
  Mule-runtime/mule-artifact-ast/1.5.6,
  Mule-runtime/mule-properties-api/1.5.6-WITH-W-18622349,
  DataWeave/data-weave/support/4.9.x,
  Mule-runtime/mule-maven-client/2.4.6
# Comment public setting to get oldMuleArtifact 4.2.1 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true -T1C
mavenCompileGoal: clean install -U -DskipTests -DskipITs -Dinvoker.skip=true -Darchetype.test.skip -Dmaven.javadoc.skip
projectType: runtime
mavenTool: "3.9.9"
jdkTool: OPEN-JDK17
additionalTestConfigs:
  jdk21:
    testJdkTool: TEMURIN-JDK21
