upstreamProjects:
  Mule-runtime/metadata-model-api/support/1.5.x,
  Mule-runtime/mule-profiling-api/support/1.1.x,
  Mule-runtime/mule-api/support/1.5.x,
  Mule-runtime/mule-extensions-api/support/1.5.x,
  Mule-runtime/mule-artifact-ast/support/1.1.x,
  Mule-runtime/mule-properties-api/master,
  DataWeave/data-weave/master,
  Mule-runtime/mule-maven-client/support/2.0.x
# Comment public setting to get oldMuleArtifact 4.2.1 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true -T1C
mavenCompileGoal: clean install -U -DskipTests -DskipITs -Dinvoker.skip=true -Darchetype.test.skip -Dmaven.javadoc.skip
projectType: runtime
# TODO W-13029381 Change to 17
jdkTool: OPEN-JDK11
additionalTestConfigs:
  jdk8:
    testJdkTool: OPEN-JDK8
# TODO W-13029381 uncomment when default changes to java 17
  #jdk11:
    #testJdkTool: OPEN-JDK11
  jdk17:
    testJdkTool: OPEN-JDK17
    mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true -T1C
    