upstreamProjects:
  Mule-runtime/metadata-model-api/support/1.4.x,
  Mule-runtime/mule-profiling-api/support/1.0.x,
  Mule-runtime/mule-api/support/1.4.x,
  Mule-runtime/mule-extensions-api/support/1.4.x,
  Mule-runtime/mule-artifact-ast/support/1.0.x,
  Mule-runtime/mule-properties-api/1.0.0-JULY-2025,
  DataWeave/data-weave/support/2.4.0,
  Mule-runtime/mule-maven-client/support/1.6.x
# Comment public setting to get oldMuleArtifact 4.2.1 from private repo till we move them to the public Repo
# Uncomment it after they are copied
# "mavenSettingsXmlId" : "mule-runtime-maven-settings-MuleSettings",
mavenAdditionalArgs: -Djava.net.preferIPv4Stack=true
mavenCompileGoal: clean install -U -DskipTests -DskipITs -Dinvoker.skip=true -Darchetype.test.skip -Dmaven.javadoc.skip
projectType: runtime
