/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.tck.util;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.List;

import org.apache.commons.dbutils.QueryRunner;
import org.apache.commons.dbutils.handlers.ArrayListHandler;
import org.junit.AfterClass;

/**
 *
 */
public class MuleDerbyTestDatabase
{

    private final String databaseNameProperty;
    String connectionString;

    public MuleDerbyTestDatabase(String databaseNameProperty)
    {
        this.databaseNameProperty = databaseNameProperty;
    }

    public void startDatabase() throws Exception
    {
        String dbName = MuleDerbyTestUtils.loadDatabaseName("derby.properties", databaseNameProperty);
        MuleDerbyTestUtils.defaultDerbyCleanAndInit("derby.properties", databaseNameProperty);
        connectionString = "jdbc:derby:" + dbName;
        emptyTestTable();
    }

    @AfterClass
    public void stopDatabase() throws SQLException
    {
        MuleDerbyTestUtils.stopDatabase();
    }

    public void emptyTestTable() throws Exception
    {
        try
        {
            execSqlUpdate("DELETE FROM TEST");
        }
        catch (Exception e)
        {
            execSqlUpdate("CREATE TABLE TEST(ID INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 0) NOT NULL PRIMARY KEY,DATA VARCHAR(255), TYPE NUMERIC, ACK NUMERIC)");
        }
    }

    public void insertIntoTest(String data, int type)
    {
        try
        {
            execSqlUpdate("INSERT into Test (data, type) VALUES ('" + data + "', " + type + ")");
        }
        catch (Exception e)
        {
            throw new RuntimeException(e);
        }
    }

    public Connection getConnection() throws Exception
    {
        Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
        return DriverManager.getConnection(connectionString);
    }

    public List execSqlQuery(String sql) throws Exception
    {
        Connection con = null;
        try
        {
            con = getConnection();
            return (List)new QueryRunner().query(con, sql, new ArrayListHandler());
        }
        finally
        {
            if (con != null && !con.isClosed())
            {
                con.close();
            }
        }
    }

    public int execSqlUpdate(String sql) throws Exception
    {
        Connection con = null;
        try
        {
            con = getConnection();
            return new QueryRunner().update(con, sql);
        }
        finally
        {
            if (con != null && !con.isClosed())
            {
                con.close();
            }
        }
    }
}
