/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.example.employee;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2016-10-21T11:05:29.862-03:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://employee.example.mule.org/", name = "EmployeeDirectory")
@XmlSeeAlso({ObjectFactory.class})
public interface EmployeeDirectory {

  @WebMethod
  @RequestWrapper(localName = "addEmployee", targetNamespace = "http://employee.example.mule.org/",
      className = "org.mule.example.employee.AddEmployee")
  @ResponseWrapper(localName = "addEmployeeResponse", targetNamespace = "http://employee.example.mule.org/",
      className = "org.mule.example.employee.AddEmployeeResponse")
  public void addEmployee(
                          @WebParam(name = "employee", targetNamespace = "http://employee.example.mule.org/") Employee employee);

  @WebMethod
  @RequestWrapper(localName = "getEmployees", targetNamespace = "http://employee.example.mule.org/",
      className = "org.mule.example.employee.GetEmployees")
  @ResponseWrapper(localName = "getEmployeesResponse", targetNamespace = "http://employee.example.mule.org/",
      className = "org.mule.example.employee.GetEmployeesResponse")
  @WebResult(name = "return", targetNamespace = "http://employee.example.mule.org/")
  public java.util.List<Employee> getEmployees();
}
