/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.runtime.core.policy;

import org.mule.runtime.dsl.api.component.ComponentIdentifier;

import java.util.Optional;

/**
 * Implementation of this interface must provide access to the policies to be applied
 * to message sources or operations.
 *
 * @since 4.0
 */
public interface PolicyProvider {

  /**
   * Creates a policy to be applied to a source. The creation must have into consideration the {@code executionIdentifier} to keep
   * track of the state of the policy. A source policy state may be propagated to an operation policy instance. For the same
   * message processing, the same {@code executionIdentifier} will be used.
   * 
   * @param executionIdentifier the unique identifier associated to the exection of a policy instance.
   * @param sourceIdentifier the identifier of the message source
   * @return a {@link Policy} associated to that source.
   */
  Optional<Policy> findSourcePolicyInstance(String executionIdentifier, ComponentIdentifier sourceIdentifier);

  /**
   * Creates a policy to be applied to an operation. The creation must have into consideration the {@code executionIdentifier} to
   * keep track of the state of the policy and correlate any previous policy state for the same execution. For the same message
   * processing, the same {@code executionIdentifier} will be used.
   *
   * @param executionIdentifier the unique identifier associated to the exection of a policy instance.
   * @param operationIdentifier the identifier of the operation.
   * @return a {@link Policy} associated to that source.
   */
  Optional<Policy> findOperationPolicy(String executionIdentifier, ComponentIdentifier operationIdentifier);

  /**
   * Disposes any resource associated to the given {@code executionIdentifier}.
   * Any exception generated by this method will be just logged and discarded.
   *
   * @param executionIdentifier identifier used for previous policies executions.
   */
  void dispose(String executionIdentifier);

}
