/*
 * (c) 2003-2014 MuleSoft, Inc. This software is protected under international copyright
 * law. All use of this software is subject to MuleSoft's Master Subscription Agreement
 * (or other master license agreement) separately entered into in writing between you and
 * MuleSoft. If such an agreement is not in place, you may not use the software.
 */
package org.mule.module.cxf;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2012-01-18T22:08:37.809-03:00
 * Generated source version: 2.5.1
 * 
 */
@WebServiceClient(name = "HolderServiceService", 
                  wsdlLocation = "/Users/evangelinamartinezruizmoreno/echoHolder.wsdl",
                  targetNamespace = "http://cxf.module.mule.org/") 
public class HolderServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://cxf.module.mule.org/", "HolderServiceService");
    public final static QName HolderServicePort = new QName("http://cxf.module.mule.org/", "HolderServicePort");
    static {
        URL url = null;
        try {
            url = new URL("/Users/evangelinamartinezruizmoreno/echoHolder.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HolderServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "/Users/evangelinamartinezruizmoreno/echoHolder.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HolderServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HolderServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HolderServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    /**
     *
     * @return
     *     returns HolderService
     */
    @WebEndpoint(name = "HolderServicePort")
    public HolderService getHolderServicePort() {
        return super.getPort(HolderServicePort, HolderService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HolderService
     */
    @WebEndpoint(name = "HolderServicePort")
    public HolderService getHolderServicePort(WebServiceFeature... features) {
        return super.getPort(HolderServicePort, HolderService.class, features);
    }

}
