/*
 * Copyright (c) MuleSoft, Inc.  All rights reserved.  http://www.mulesoft.com
 * The software in this package is published under the terms of the CPAL v1.0
 * license, a copy of which has been included with this distribution in the
 * LICENSE.txt file.
 */
package org.mule.module.http.internal.listener;

import org.mule.api.DefaultMuleException;
import org.mule.api.MuleContext;
import org.mule.api.MuleException;
import org.mule.module.http.api.listener.HttpListenerConfig;
import org.mule.transport.ssl.TlsContextFactory;

import java.util.concurrent.atomic.AtomicInteger;

public class HttpListenerConfigBuilder
{

    private final DefaultHttpListenerConfig config;
    private final static AtomicInteger autoGeneratedConfigIndex = new AtomicInteger(0);
    private final MuleContext muleContext;

    public HttpListenerConfigBuilder(final String name, final MuleContext muleContext)
    {
        this.config = new DefaultHttpListenerConfig();
        this.config.setMuleContext(muleContext);
        this.config.setName(name);
        this.muleContext = muleContext;
    }

    public HttpListenerConfigBuilder(final MuleContext muleContext)
    {
        this(getNextAutoGeneratedConfigName(), muleContext);
    }

    private static String getNextAutoGeneratedConfigName()
    {
        return String.format("auto-generated-listener-config-%s", autoGeneratedConfigIndex.getAndIncrement());
    }

    public HttpListenerConfigBuilder setPort(int port)
    {
        this.config.setPort(port);
        return this;
    }

    public HttpListenerConfigBuilder setHost(String host)
    {
        this.config.setHost(host);
        return this;
    }

    public HttpListenerConfigBuilder setTlsContextFactory(TlsContextFactory tlsContextFactory)
    {
        this.config.setTlsContext(tlsContextFactory);
        return this;
    }

    public HttpListenerConfig build() throws MuleException
    {
        try
        {
            this.muleContext.getRegistry().registerObject(this.config.getName(), this.config);
            this.config.initialise();
            this.config.start();
            return this.config;
        }
        catch (Exception e)
        {
            throw new DefaultMuleException(e);
        }
    }
}
