<?xml version='1.0' encoding='UTF-8' ?>
<definitions  name ='SoapResponder'   targetNamespace = 'http://www.SoapClient.com/xml/SoapResponder.wsdl'
              xmlns:tns='http://www.SoapClient.com/xml/SoapResponder.wsdl'
              xmlns:xsd1='http://www.SoapClient.com/xml/SoapResponder.xsd'
              xmlns:xsd='http://www.w3.org/2001/XMLSchema'
              xmlns:soap='http://schemas.xmlsoap.org/wsdl/soap/'
              xmlns='http://schemas.xmlsoap.org/wsdl/'>
    <types>
        <schema targetNamespace='http://www.SoapClient.com/xml/SoapResponder.xsd'
                xmlns='http://www.w3.org/1999/XMLSchema'>
        </schema>
    </types>
    <message name='Method1'>
        <part name='bstrParam1' type='xsd:string'/>
        <part name='bstrParam2' type='xsd:string'/>
    </message>
    <message name='Method1Response'>
        <part name='bstrReturn' type='xsd:string'/>
    </message>
    <portType name='SoapResponderPortType'>
        <operation name='Method1' parameterOrder='bstrparam1 bstrparam2 return'>
            <input message='tns:Method1' />
            <output message='tns:Method1Response' />
        </operation>
    </portType>
    <binding name='SoapResponderBinding' type='tns:SoapResponderPortType' >
        <soap:binding style='rpc' transport='http://schemas.xmlsoap.org/soap/http' />
        <operation name='Method1' >
            <soap:operation soapAction='http://www.SoapClient.com/SoapObject' />
            <input>
                <soap:body use='encoded' namespace='http://www.SoapClient.com/xml/SoapResponder.xsd'  encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' />
            </input>
            <output>
                <soap:body use='encoded' namespace='http://www.SoapClient.com/xml/SoapResponder.xsd'  encodingStyle='http://schemas.xmlsoap.org/soap/encoding/' />
            </output>
        </operation>
    </binding>
    <service name='SoapResponder' >
        <documentation>A SOAP service that echoes input parameters in the response</documentation>
        <port name='SoapResponderPortType' binding='tns:SoapResponderBinding' >
            <soap:address location='http://www.soapclient.com/xml/soapresponder.wsdl' />
        </port>
    </service>
</definitions>
