<?xml version='1.0' encoding='UTF-8'?>
<wsdl:definitions xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://consumer.ws.module.mule.org/"
                  xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
                  name="TestService" targetNamespace="http://consumer.ws.module.mule.org/">

    <!--
    This is another WSDL for the TestService, but imports the types from a separate WSDL "TestIncludedTypeDefinitions.wsdl".
    -->

    <wsdl:import namespace="http://consumer.ws.module.mule.org/" location="TestIncludedTypeDefinitions.wsdl"/>
    <wsdl:types />
    <wsdl:binding name="TestServiceSoapBinding" type="tns:TestService">
        <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="noParams">
            <soap:operation soapAction="noParams" style="document"/>
            <wsdl:input name="noParams">
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output name="noParamsResponse">
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
    <wsdl:service name="TestService">
        <wsdl:port binding="tns:TestServiceSoapBinding" name="TestPort">
            <soap:address location="http://localhost:5804/services/Test"/>
        </wsdl:port>
    </wsdl:service>
</wsdl:definitions>